import {createParameterType} from '@sanity/gherkin-driver'
import {parseGherkinTextParameter} from './gherkin-step-helpers'

export const parameterTypes = [
  createParameterType(
    'annotation',
    /"(comment|link)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'block-object',
    /"(image)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'index',
    /"(\d)"/,
    Number,
    (input) => Number.parseInt(input, 10),
    false,
    true,
  ),
  createParameterType(
    'inline-object',
    /"(stock-ticker)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'button',
    /"(ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Backspace|Delete|Enter|Space)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'key',
    /"([a-z]\d)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'keys',
    /"(([a-z]\d)(,([a-z]\d))*)"/,
    Array,
    (input) => input.split(','),
    false,
    true,
  ),
  createParameterType(
    'decorator',
    /"(em|strong)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'marks',
    /"((strong|em|[a-z]\d)(,(strong|em|[a-z]\d))*)"/,
    Array,
    (input) => input.split(','),
    false,
    true,
  ),
  createParameterType(
    'style',
    /"(normal|h1)"/,
    String,
    (input) => input,
    false,
    true,
  ),
  createParameterType(
    'text',
    /"([a-z-,\\n |]*)"/,
    Array,
    parseGherkinTextParameter,
    false,
    true,
  ),
]
