packages:
  - 'apps/*'
  - 'packages/*'
  - 'examples/*'

catalog:
  typescript: 5.9.3

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@portabletext/*'
  - '@sanity/*'
  - '@types/*'
  - '@typescript/*'
  - csstype
  - 'groq-js'
  - 'react'
  - 'react-dom'
  - 'react-is'
  # Renovate security update: markdown-it@14.1.1
  - markdown-it@14.1.1

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@reduxjs/toolkit@2.9.0 || 2.10.1 || 2.11.0'
  - '@sanity/mutate@0.11.0-canary.4'
  - '@sanity/sdk@2.1.2'
  - '@swc/core@1.13.5'
  - chokidar@4.0.3
  - groq@3.88.1-typegen-experimental.0
  - react-redux@9.2.0
  - reselect@5.1.1
  - rxjs@7.8.2
  - semver@5.7.2 || 6.3.1
  - undici@5.29.0
  - undici-types@6.21.0
  - vite@5.4.21 || 6.4.1
