/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarkdownRouteImport } from './routes/markdown'
import { Route as MinimalRouteImport } from './routes/minimal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownRoute = MarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimalRoute = MinimalRouteImport.update({
  id: '/minimal',
  path: '/minimal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markdown': typeof MarkdownRoute
  '/minimal': typeof MinimalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markdown': typeof MarkdownRoute
  '/minimal': typeof MinimalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markdown': typeof MarkdownRoute
  '/minimal': typeof MinimalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/markdown' | '/minimal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/markdown' | '/minimal'
  id: '__root__' | '/' | '/markdown' | '/minimal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarkdownRoute: typeof MarkdownRoute
  MinimalRoute: typeof MinimalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown': {
      id: '/markdown'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof MarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimal': {
      id: '/minimal'
      path: '/minimal'
      fullPath: '/minimal'
      preLoaderRoute: typeof MinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarkdownRoute: MarkdownRoute,
  MinimalRoute: MinimalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
