name: bundle-stats

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  bundle-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install project dependencies
        run: pnpm install

      - uses: rexxars/bundle-stats@v1
        with:
          packages: "packages/editor"
          build-command: pnpm build --filter @portabletext/editor...
          ignore: "test, test/vitest"
