name: check-react-compiler

on:
  # Build on pushes branches that have a PR (including drafts)
  pull_request:
  # Build on commits pushed to branches without a PR if it's in the allowlist
  push:
    branches: [main]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install project dependencies
        run: pnpm install

      - name: Check react compiler on editor
        working-directory: packages/editor
        run: pnpm check:react-compiler -f gha

      - name: Check react compiler on toolbar
        working-directory: packages/toolbar
        run: pnpm check:react-compiler -f gha

      - name: Check react compiler on playground
        working-directory: apps/playground
        run: pnpm check:react-compiler -f gha
