name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'renovate[bot]'
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSCRIPT_APP_ID }}
          private-key: ${{ secrets.ECOSCRIPT_APP_PRIVATE_KEY }}
      - uses: mscharley/dependency-changesets-action@9627b26cfcbc22fa47cc45d8e9d79107e3909965 # v1.1.7
        with:
          token: ${{ steps.app-token.outputs.token }}
          use-conventional-commits: true
          sign-commits: true
